version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-liferay
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: liferaydb
      MYSQL_USER: liferay
      MYSQL_PASSWORD: liferay
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - liferay-net

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - liferay-net

networks:
  liferay-net:
    driver: bridge
